### ISSUE TITLE
Relying on Extension

### ISSUE THREAD

**Issue by terminalforlife** [xvoland/Extract#11]
While I'm sure it works most of the time, what about files which don't have a traditional extension, or one at all?

EDIT:

Okay, basically, this is what I had in mind. Thought I'd just write it myself as I figured it would be pretty neat:

https://github.com/terminalforlife/miscellaneous/blob/dev/unpack

Do you think this approach is something you would consider incorporating into your function?

**Comment by xvoland** [comment]
It's looks nice, but it has additional dependencies like _mimetype_ and so I think this is not good idea
