### ISSUE TITLE
What if file has a space character in filename?

### ISSUE THREAD

**Issue by freed00m** [xvoland/Extract#14]
Hi,

This extractor works great but if the filename has a space character it fails to extract even if I use `"` or `'`.
It says file not exists because it tried to use only the sup before the first space.

If it's not possible due to bash limitation it would be helpful to mention it in README.

**Comment by freed00m** [comment]
At line 10?

```
for n in $@
```

Should be?

```
for n in "$@"
```

I am no bash expert but it fixes for me.

**Comment by xvoland** [comment]
Hi,
I made some changes, as you ask, but it doesn't solve to the end, as it seems to me :(
of course, can play with "$@" and $*.... let it be so for now ;)
