### ISSUE TITLE
Extract on PATH

### ISSUE THREAD

**Issue by stdedos** [xvoland/Extract#16]
Would you accept patches to make this executable instead?

I am locally making it "executable", but https://github.com/xvoland/Extract/blob/dda4c334818863781574b2315950c6ef569c2531/extract.sh#L4-L5 lines confuse me as how to handle it (or why are they there in the first place).

I think that https://github.com/xvoland/Extract/commit/42c38af09ca57b84e017b779e0c58c4c13928ea3 should be solved "externally" [i.e. user is responsible to give a correct path], rather you trying to "mask" it.

**Comment by xvoland** [comment]
Hello, of course, patches are accepted, but I'm not so quick in making decisions need or not this functionality, or how to better - sorry...
I need to think about it.
Thanks for your patch!

**Comment by xvoland** [comment]
This variable determines how Bash recognizes fields, or word boundaries, when it interprets character strings.

$IFS defaults to whitespace (space, tab, and newline), but may be changed, for example, to parse a comma-separated data file.

1fd7c045a8ea9021765dad9276e8cd247d317154
