### ISSUE TITLE
lessmsi

### ISSUE THREAD

**Issue by cup** [xvoland/Extract#18]
better for MSI files

https://github.com/activescott/lessmsi

**Comment by xvoland** [comment]
> This is a utility with a graphical user interface
How does this relate to the command line utility? Or I didn't understand something?

**Comment by cup** [comment]
~~~
lessmsi x aa.msi
~~~

**Comment by xvoland** [comment]
I think this is a bad idea and would not want to be tied to the platform.

Thank you for your time
