### ISSUE TITLE
Invalid path argument given to uncompression programs

### ISSUE THREAD

**Issue by marcwrobel** [xvoland/Extract#2]
Since commit 2f89a4ade1443a4f01f96e7628125835cf98bf0e and the "make dir" removal the function gives invalid compressed file path to uncompression programs. `../"$1"` should be either transformed to `"$1"` or turned into a variable (`path` for instance) :
```bash
local path="$1"
# local basename=${1%.*}
# mkdir $basename && cd $basename 
# path="../$1"
```

**Comment by xvoland** [comment]
Thanks, will be fixed

**Comment by xvoland** [comment]
Please check

**Comment by xvoland** [comment]
Please, check. Fixed.
