### ISSUE TITLE
bash script and function confusion

### ISSUE THREAD

**Issue by ruzito** [xvoland/Extract#34]
Hello correct me if I'm wrong but,

- doing `PATH=script_dir/extract.sh:$PATH` seems highly irregular
- It doesn't actually work, the bash function extract is not being run anywhere

I propose to change the `README.md` so that the installation step of adding the file to path is:
```bash
export PATH="<path_to_file>":"$PATH"
```
(`"$PATH"` so that any possible preexisting spaces in the path are properly escaped)
and that the `extract.sh` has an additional line:
```bash
extract "$@"
```

**Comment by ComedyTomedy** [comment]
The readme is auto-generated with ChatGPT or similar, and yes it's completely wrong.

**Comment by xvoland** [comment]
I'm not like ChatGPT and the readme is not automatically generated.
