### ISSUE TITLE
Include a LICENSE

### ISSUE THREAD

**Issue by keithieopia** [xvoland/Extract#7]
The README.md does specify the MIT license, but you should include the license text since the MIT license requires it be provided in order for others to use your code:
>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. 

Preferably, it should be in a separate LICENSE file. Plus, GitHub will give you a nifty little icon in the top commit bar, if you do use a LICENSE file.

**Comment by xvoland** [comment]
Thank you! [Done](https://github.com/xvoland/Extract/commit/31f82f730c02d9c7110f3a91e319a71c9dc9a992).
