### ISSUE TITLE
extract multiple files

### ISSUE THREAD

**Issue by burianvlastimil** [xvoland/Extract#8]
Today I ran:

```
extract *.zip
```

but it extracted only the first archive.

Would it be possible to incorporate multiple files extraction?

**Comment by xvoland** [comment]
Hi,
My apologize for the delay, in the near future I'll try to implement it. Thanks for idea.

**Comment by xvoland** [comment]
Done. Testing requires not only for errors but also usability

`60f9ac56f774d9db04e8989e35a881c700ec96a9`
