### ISSUE TITLE
DMG files

### ISSUE THREAD

**Issue by ComedyTomedy** [xvoland/Extract#9]
Sorry, don't know how to pull-request, but DMG (Apple Disk iMaGe, like an ISO) is an archive format that can be opened with 7z, so I just added it to the case statement:

*.7z|*.dmg)

**Comment by xvoland** [comment]
OK, I'll check it

**Comment by xvoland** [comment]
Added support for arj, cab, chm, deb, dmg, iso, lzh, msi, rpm, udf, wim, xar
